
site_name: Documentation

nav:
  - Home: 'index.md'


  - 'Straight Road':
        - "Speed" : 'straight_speed.md'
        - "Accerelation" : 'scenario-1.md'
        - "Acceralation all data" : 'straight_acc.md'
  - 'Curved Road' :
        - "Speed": 'curved_speed.md'
        - "Accerelation": 'scenario-2.md'
        - "Acceralation all data": 'curved_acc.md'


theme:
  name: material
  language: en
  palette:
    primary: black
    accent: red
  font:
    text: Ubuntu
    code: Ubuntu Mono

markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - markdown.extensions.codehilite:
      guess_lang: false

plugins:
  - search
  - minify:
      minify_html: true
